### ISSUE TITLE
Mark todos logic

### ISSUE THREAD

**Issue by shiryz** [facn6/AKWeek3#6]
The following lines in marktodos function can be more readable and shortened
https://github.com/facn6/AKWeek3/blob/master/logic.js#L50
```js
if (curr.done == true) curr.done = false;
        else {
          curr.done = true;
        }
        return curr;
      } else {
        return curr;
      }
```
What you're trying to do is change the state of the todo from true to false and vice versa and this can be done by returning the opposite state
```js
curr.done = !curr.done;
return curr;
```

**Comment by ayahkh** [comment]
done
